version: "3"
services:
  Front-End:
    build: ./loja-front
    image: node-react
    ports:
        - 3001:3000
    volumes:
        - ./loja-front:/home/front/
  Express:
    build: ./server
    image: node-express
    ports:
      - 2020:2020
    volumes:
      - ./server:/home/back

  Mongo-DB:
    image: mongo
    ports: 
      - 27018:27017
    volumes:
      - ./data:/data/db  